version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "db"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: birdoldb
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local
