version: '3'
services:
  api:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    environment:
      GIN_MODE: debug 
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_ADDRESS: db
      DB_NAME: ${MYSQL_DATABASE}
      API_VERSION: v2
      TZ: 'Asia/Tokyo'
      PORT: 80
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app
    ports:
      - 8080:80
    depends_on:
      - "db"
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local
