name: Build & Push Docker Image

on:
  push:
    branches: [ "main", "dev/**" ]
  
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38
        with:
          files: |
            .github/workflows/deploy_ghcr.yml
            api/**
            Dockerfile

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        if: steps.changed-files.outputs.any_changed == 'true'

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=sha,format=long

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ghcr容量の無制限無料期間が終わったら、以下を使ってghcrの最新n件のみ残すように変更する。まだghcrがサポートされていない。
      # https://github.com/actions/delete-package-versions
